version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install pnpm
          command: npm install -g pnpm
      - run:
          name: install dependencies
          command: pnpm install
      - run:
          name: release
          command: pnpm run semantic-release || true
